### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by Fraze** [usgo/gocongress#184] opened 2021-04-09 01:16 UTC
Would be helpful to TD's to send an email validation link so we can ensure that people input their email correctly and that they own them

**Comment by jaredbeck** [comment] 2021-04-09 03:48
should be easy to add. confirmation is a built-in feature of the authentication library we use

https://www.rubydoc.info/github/heartcombo/devise/master/Devise/Models/Confirmable

should just have to turn it on, maybe add a db column or two

**Comment by neagle** [comment] 2021-04-09 13:14
That's helpful to know, Jared. Email confirmation is certainly a pretty standard part of a lot of signup flows now.

It's a bit of a question how we'd handle it for family registrations, though: the Congress site is set up to let single users register whole groups of other users, since we have many people signing up for families. Requring one email validation as part of creating a user account seems okay, but whether it'd work to validate any other attendees they register is a more difficult question.

Out of curiosity, is this a problem that came up for you, Devin?

**Comment by Fraze** [comment] 2021-04-10 03:10
Single email for families should be fine for my/our use case. Basically, Jon mentioned to me he was unable to contact some of his event participants last year due to invalid emails.

**Comment by neagle** [comment] 2021-05-18 02:36
Looks like this is a duplicate of #34.

**Closed** 2021-06-11 22:56 UTC
