### ISSUE TITLE
Attendees under the age of 18 are shown on "Who is Coming" list

### ISSUE THREAD

**Issue by 0lionelzhang0** [usgo/gocongress#257] opened 2021-06-30 21:14 UTC
## Summary of the Bug
Every attendee is shown in the "Who is Coming" list, including minors.

## Steps to Reproduce the Behaviour
1. Go to https://www.gocongress.org/2021/attendees
2. Scroll down to the bottom and see the number of displayed attendees is the same as the total attendees.

## The Expected Behaviour
"Who is Coming" list excludes minors.

## Screenshots
![image](https://user-images.githubusercontent.com/36424267/124032075-f56b8a00-d9ac-11eb-85f6-10d77856f21e.png)

**Comment by neagle** [comment] 2021-07-01 00:26
It looks like I introduced this regression when I updated the "Who's Coming" page for online Congresses so that it wouldn't require all the normal conditions (like having a plan, having paid $70 toward it, &c). Thank you _very_ much for reporting this.

This is fixed by #4f664fb36b7bc1a04e61442b229ecd21d2201359.

**Closed by neagle** 2021-07-01 00:26 UTC
Labels: bug
