### ISSUE TITLE
Who is attending displaying an error

### ISSUE THREAD

**Issue by vash3g** [usgo/gocongress#263] opened 2021-07-03 20:49 UTC
## Summary of the Bug
If you view the who is coming page it displays an error

## Steps to Reproduce the Behaviour
1. Go to https://www.gocongress.org/2021/attendees

## The Expected Behaviour
Concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/994470/124366548-9ad96480-dc1e-11eb-8ada-e2022ca329e8.png)

**Comment by neagle** [comment] 2021-07-03 23:19
Lovely regressions. Looks like there was an error in my code for displaying the numer of pros, and it didn't break till a pro actually signed up.

Closed by fe23679096ce4fd43296a9c3393174292aa35f19.

**Closed** 2021-07-03 23:19 UTC
Labels: bug
